using System;
using System.Collections.Generic;
using System.Text;

namespace Mineman.WorldParsing.Blocks
{
    public enum BiomeType
    {
        Unknown,
        Ocean = 0,
        Plains = 1,
        Desert = 2,
        Extreme_Hills = 3,
        Forest = 4,
        Taiga = 5,
        Swampland = 6,
        River = 7,
        Hell = 8,
        Sky = 9,
        Frozen_Ocean = 10,
        Frozen_River = 11,
        Ice_Plains = 12,
        Ice_Mountains = 13,
        Mushroom_Island = 14,
        Mushroom_Island_Shore = 15,
        Beach = 16,
        Desert_Hills = 17,
        Forest_Hills = 18,
        Taiga_Hills = 19,
        Extreme_Hills_Edge = 20,
        Jungle = 21,
        Jungle_Hills = 22,
        JungleEdge = 23,
        Deep_Ocean = 24,
        Stone_Beach = 25,
        Cold_Beach = 26,
        Birch_Forest = 27,
        Birch_Forest_Hills = 28,
        Roofed_Forest = 29,
        Cold_Taiga = 30,
        Cold_Taiga_Hills = 31,
        Mega_Taiga = 32,
        Mega_Taiga_Hills = 33,
        Extreme_Hills2 = 34,
        Savanna = 35,
        Savanna_Plateau = 36,
        Mesa = 37,
        Mesa_Plateau_F = 38,
        Mesa_Plateau = 39,
        The_Void = 127,
        Sunflower_Plains = 129,
        Desert_M = 130,
        Extreme_Hills_M = 131,
        Flower_Forest = 132,
        Taiga_M = 133,
        Swampland_M = 134,
        Ice_Plains_Spikes = 140,
        Jungle_M = 149,
        JungleEdge_M = 151,
        Birch_Forest_M = 155,
        Birch_Forest_Hills_M = 156,
        Roofed_Forest_M = 157,
        Cold_Taiga_M = 158,
        Mega_Spruce_Taiga = 160,
        Redwood_Taiga_Hills_M = 161,
        Extreme_Hills2_M = 162,
        Savanna_M = 163,
        Savanna_Plateau_M = 164,
        Mesa_Bryce = 165,
        Mesa_Plateau_F_M = 166,
        Mesa_Plateau_M = 167,
    }

    public class Block
    {
        private static readonly Dictionary<string, string> blockNames = new Dictionary<string, string>
        {
            {"0","Air"},
            {"1","Stone"},
            {"1:1","Granite"},
            {"1:2","Polished Granite"},
            {"1:3","Diorite"},
            {"1:4","Polished Diorite"},
            {"1:5","Andesite"},
            {"1:6","Polished Andesite"},
            {"2","Grass"},
            {"3","Dirt"},
            {"3:1","Coarse Dirt"},
            {"3:2","Podzol"},
            {"4","Cobblestone"},
            {"5","Oak Wood Plank"},
            {"5:1","Spruce Wood Plank"},
            {"5:2","Birch Wood Plank"},
            {"5:3","Jungle Wood Plank"},
            {"5:4","Acacia Wood Plank"},
            {"5:5","Dark Oak Wood Plank"},
            {"6","Oak Sapling"},
            {"6:1","Spruce Sapling"},
            {"6:2","Birch Sapling"},
            {"6:3","Jungle Sapling"},
            {"6:4","Acacia Sapling"},
            {"6:5","Dark Oak Sapling"},
            {"7","Bedrock"},
            {"8","Flowing Water"},
            {"9","Still Water"},
            {"10","Flowing Lava"},
            {"11","Still Lava"},
            {"12","Sand"},
            {"12:1","Red Sand"},
            {"13","Gravel"},
            {"14","Gold Ore"},
            {"15","Iron Ore"},
            {"16","Coal Ore"},
            {"17","Oak Wood"},
            {"17:1","Spruce Wood"},
            {"17:2","Birch Wood"},
            {"17:3","Jungle Wood"},
            {"18","Oak Leaves"},
            {"18:1","Spruce Leaves"},
            {"18:2","Birch Leaves"},
            {"18:3","Jungle Leaves"},
            {"19","Sponge"},
            {"19:1","Wet Sponge"},
            {"20","Glass"},
            {"21","Lapis Lazuli Ore"},
            {"22","Lapis Lazuli Block"},
            {"23","Dispenser"},
            {"24","Sandstone"},
            {"24:1","Chiseled Sandstone"},
            {"24:2","Smooth Sandstone"},
            {"25","Note Block"},
            {"26","Bed"},
            {"27","Powered Rail"},
            {"28","Detector Rail"},
            {"29","Sticky Piston"},
            {"30","Cobweb"},
            {"31","Dead Shrub"},
            {"31:1","Grass"},
            {"31:2","Fern"},
            {"32","Dead Bush"},
            {"33","Piston"},
            {"34","Piston Head"},
            {"35","White Wool"},
            {"35:1","Orange Wool"},
            {"35:2","Magenta Wool"},
            {"35:3","Light Blue Wool"},
            {"35:4","Yellow Wool"},
            {"35:5","Lime Wool"},
            {"35:6","Pink Wool"},
            {"35:7","Gray Wool"},
            {"35:8","Light Gray Wool"},
            {"35:9","Cyan Wool"},
            {"35:10","Purple Wool"},
            {"35:11","Blue Wool"},
            {"35:12","Brown Wool"},
            {"35:13","Green Wool"},
            {"35:14","Red Wool"},
            {"35:15","Black Wool"},
            {"37","Dandelion"},
            {"38","Poppy"},
            {"38:1","Blue Orchid"},
            {"38:2","Allium"},
            {"38:3","Azure Bluet"},
            {"38:4","Red Tulip"},
            {"38:5","Orange Tulip"},
            {"38:6","White Tulip"},
            {"38:7","Pink Tulip"},
            {"38:8","Oxeye Daisy"},
            {"39","Brown Mushroom"},
            {"40","Red Mushroom"},
            {"41","Gold Block"},
            {"42","Iron Block"},
            {"43","Double Stone Slab"},
            {"43:1","Double Sandstone Slab"},
            {"43:2","Double Wooden Slab"},
            {"43:3","Double Cobblestone Slab"},
            {"43:4","Double Brick Slab"},
            {"43:5","Double Stone Brick Slab"},
            {"43:6","Double Nether Brick Slab"},
            {"43:7","Double Quartz Slab"},
            {"44","Stone Slab"},
            {"44:1","Sandstone Slab"},
            {"44:2","Wooden Slab"},
            {"44:3","Cobblestone Slab"},
            {"44:4","Brick Slab"},
            {"44:5","Stone Brick Slab"},
            {"44:6","Nether Brick Slab"},
            {"44:7","Quartz Slab"},
            {"45","Bricks"},
            {"46","TNT"},
            {"47","Bookshelf"},
            {"48","Moss Stone"},
            {"49","Obsidian"},
            {"50","Torch"},
            {"51","Fire"},
            {"52","Monster Spawner"},
            {"53","Oak Wood Stairs"},
            {"54","Chest"},
            {"55","Redstone Wire"},
            {"56","Diamond Ore"},
            {"57","Diamond Block"},
            {"58","Crafting Table"},
            {"59","Wheat Crops"},
            {"60","Farmland"},
            {"61","Furnace"},
            {"62","Burning Furnace"},
            {"63","Standing Sign Block"},
            {"64","Oak Door Block"},
            {"65","Ladder"},
            {"66","Rail"},
            {"67","Cobblestone Stairs"},
            {"68","Wall-mounted Sign Block"},
            {"69","Lever"},
            {"70","Stone Pressure Plate"},
            {"71","Iron Door Block"},
            {"72","Wooden Pressure Plate"},
            {"73","Redstone Ore"},
            {"74","Glowing Redstone Ore"},
            {"75","Redstone Torch (off)"},
            {"76","Redstone Torch (on)"},
            {"77","Stone Button"},
            {"78","Snow"},
            {"79","Ice"},
            {"80","Snow Block"},
            {"81","Cactus"},
            {"82","Clay"},
            {"83","Sugar Canes"},
            {"84","Jukebox"},
            {"85","Oak Fence"},
            {"86","Pumpkin"},
            {"87","Netherrack"},
            {"88","Soul Sand"},
            {"89","Glowstone"},
            {"90","Nether Portal"},
            {"91","Jack o'Lantern"},
            {"92","Cake Block"},
            {"93","Redstone Repeater Block (off)"},
            {"94","Redstone Repeater Block (on)"},
            {"95","White Stained Glass"},
            {"95:1","Orange Stained Glass"},
            {"95:2","Magenta Stained Glass"},
            {"95:3","Light Blue Stained Glass"},
            {"95:4","Yellow Stained Glass"},
            {"95:5","Lime Stained Glass"},
            {"95:6","Pink Stained Glass"},
            {"95:7","Gray Stained Glass"},
            {"95:8","Light Gray Stained Glass"},
            {"95:9","Cyan Stained Glass"},
            {"95:10","Purple Stained Glass"},
            {"95:11","Blue Stained Glass"},
            {"95:12","Brown Stained Glass"},
            {"95:13","Green Stained Glass"},
            {"95:14","Red Stained Glass"},
            {"95:15","Black Stained Glass"},
            {"96","Wooden Trapdoor"},
            {"97","Stone Monster Egg"},
            {"97:1","Cobblestone Monster Egg"},
            {"97:2","Stone Brick Monster Egg"},
            {"97:3","Mossy Stone Brick Monster Egg"},
            {"97:4","Cracked Stone Brick Monster Egg"},
            {"97:5","Chiseled Stone Brick Monster Egg"},
            {"98","Stone Bricks"},
            {"98:1","Mossy Stone Bricks"},
            {"98:2","Cracked Stone Bricks"},
            {"98:3","Chiseled Stone Bricks"},
            {"99","Brown Mushroom Block"},
            {"100","Red Mushroom Block"},
            {"101","Iron Bars"},
            {"102","Glass Pane"},
            {"103","Melon Block"},
            {"104","Pumpkin Stem"},
            {"105","Melon Stem"},
            {"106","Vines"},
            {"107","Oak Fence Gate"},
            {"108","Brick Stairs"},
            {"109","Stone Brick Stairs"},
            {"110","Mycelium"},
            {"111","Lily Pad"},
            {"112","Nether Brick"},
            {"113","Nether Brick Fence"},
            {"114","Nether Brick Stairs"},
            {"115","Nether Wart"},
            {"116","Enchantment Table"},
            {"117","Brewing Stand"},
            {"118","Cauldron"},
            {"119","End Portal"},
            {"120","End Portal Frame"},
            {"121","End Stone"},
            {"122","Dragon Egg"},
            {"123","Redstone Lamp (inactive)"},
            {"124","Redstone Lamp (active)"},
            {"125","Double Oak Wood Slab"},
            {"125:1","Double Spruce Wood Slab"},
            {"125:2","Double Birch Wood Slab"},
            {"125:3","Double Jungle Wood Slab"},
            {"125:4","Double Acacia Wood Slab"},
            {"125:5","Double Dark Oak Wood Slab"},
            {"126","Oak Wood Slab"},
            {"126:1","Spruce Wood Slab"},
            {"126:2","Birch Wood Slab"},
            {"126:3","Jungle Wood Slab"},
            {"126:4","Acacia Wood Slab"},
            {"126:5","Dark Oak Wood Slab"},
            {"127","Cocoa"},
            {"128","Sandstone Stairs"},
            {"129","Emerald Ore"},
            {"130","Ender Chest"},
            {"131","Tripwire Hook"},
            {"132","Tripwire"},
            {"133","Emerald Block"},
            {"134","Spruce Wood Stairs"},
            {"135","Birch Wood Stairs"},
            {"136","Jungle Wood Stairs"},
            {"137","Command Block"},
            {"138","Beacon"},
            {"139","Cobblestone Wall"},
            {"139:1","Mossy Cobblestone Wall"},
            {"140","Flower Pot"},
            {"141","Carrots"},
            {"142","Potatoes"},
            {"143","Wooden Button"},
            {"144","Mob Head"},
            {"145","Anvil"},
            {"146","Trapped Chest"},
            {"147","Weighted Pressure Plate (light)"},
            {"148","Weighted Pressure Plate (heavy)"},
            {"149","Redstone Comparator (inactive)"},
            {"150","Redstone Comparator (active)"},
            {"151","Daylight Sensor"},
            {"152","Redstone Block"},
            {"153","Nether Quartz Ore"},
            {"154","Hopper"},
            {"155","Quartz Block"},
            {"155:1","Chiseled Quartz Block"},
            {"155:2","Pillar Quartz Block"},
            {"156","Quartz Stairs"},
            {"157","Activator Rail"},
            {"158","Dropper"},
            {"159","White Hardened Clay"},
            {"159:1","Orange Hardened Clay"},
            {"159:2","Magenta Hardened Clay"},
            {"159:3","Light Blue Hardened Clay"},
            {"159:4","Yellow Hardened Clay"},
            {"159:5","Lime Hardened Clay"},
            {"159:6","Pink Hardened Clay"},
            {"159:7","Gray Hardened Clay"},
            {"159:8","Light Gray Hardened Clay"},
            {"159:9","Cyan Hardened Clay"},
            {"159:10","Purple Hardened Clay"},
            {"159:11","Blue Hardened Clay"},
            {"159:12","Brown Hardened Clay"},
            {"159:13","Green Hardened Clay"},
            {"159:14","Red Hardened Clay"},
            {"159:15","Black Hardened Clay"},
            {"160","White Stained Glass Pane"},
            {"160:1","Orange Stained Glass Pane"},
            {"160:2","Magenta Stained Glass Pane"},
            {"160:3","Light Blue Stained Glass Pane"},
            {"160:4","Yellow Stained Glass Pane"},
            {"160:5","Lime Stained Glass Pane"},
            {"160:6","Pink Stained Glass Pane"},
            {"160:7","Gray Stained Glass Pane"},
            {"160:8","Light Gray Stained Glass Pane"},
            {"160:9","Cyan Stained Glass Pane"},
            {"160:10","Purple Stained Glass Pane"},
            {"160:11","Blue Stained Glass Pane"},
            {"160:12","Brown Stained Glass Pane"},
            {"160:13","Green Stained Glass Pane"},
            {"160:14","Red Stained Glass Pane"},
            {"160:15","Black Stained Glass Pane"},
            {"161","Acacia Leaves"},
            {"161:1","Dark Oak Leaves"},
            {"162","Acacia Wood"},
            {"162:1","Dark Oak Wood"},
            {"163","Acacia Wood Stairs"},
            {"164","Dark Oak Wood Stairs"},
            {"165","Slime Block"},
            {"166","Barrier"},
            {"167","Iron Trapdoor"},
            {"168","Prismarine"},
            {"168:1","Prismarine Bricks"},
            {"168:2","Dark Prismarine"},
            {"169","Sea Lantern"},
            {"170","Hay Bale"},
            {"171","White Carpet"},
            {"171:1","Orange Carpet"},
            {"171:2","Magenta Carpet"},
            {"171:3","Light Blue Carpet"},
            {"171:4","Yellow Carpet"},
            {"171:5","Lime Carpet"},
            {"171:6","Pink Carpet"},
            {"171:7","Gray Carpet"},
            {"171:8","Light Gray Carpet"},
            {"171:9","Cyan Carpet"},
            {"171:10","Purple Carpet"},
            {"171:11","Blue Carpet"},
            {"171:12","Brown Carpet"},
            {"171:13","Green Carpet"},
            {"171:14","Red Carpet"},
            {"171:15","Black Carpet"},
            {"172","Hardened Clay"},
            {"173","Block of Coal"},
            {"174","Packed Ice"},
            {"175","Sunflower"},
            {"175:1","Lilac"},
            {"175:2","Double Tallgrass"},
            {"175:3","Large Fern"},
            {"175:4","Rose Bush"},
            {"175:5","Peony"},
            {"176","Free-standing Banner"},
            {"177","Wall-mounted Banner"},
            {"178","Inverted Daylight Sensor"},
            {"179","Red Sandstone"},
            {"179:1","Chiseled Red Sandstone"},
            {"179:2","Smooth Red Sandstone"},
            {"180","Red Sandstone Stairs"},
            {"181","Double Red Sandstone Slab"},
            {"182","Red Sandstone Slab"},
            {"183","Spruce Fence Gate"},
            {"184","Birch Fence Gate"},
            {"185","Jungle Fence Gate"},
            {"186","Dark Oak Fence Gate"},
            {"187","Acacia Fence Gate"},
            {"188","Spruce Fence"},
            {"189","Birch Fence"},
            {"190","Jungle Fence"},
            {"191","Dark Oak Fence"},
            {"192","Acacia Fence"},
            {"193","Spruce Door Block"},
            {"194","Birch Door Block"},
            {"195","Jungle Door Block"},
            {"196","Acacia Door Block"},
            {"197","Dark Oak Door Block"},
            {"198","End Rod"},
            {"199","Chorus Plant"},
            {"200","Chorus Flower"},
            {"201","Purpur Block"},
            {"202","Purpur Pillar"},
            {"203","Purpur Stairs"},
            {"204","Purpur Double Slab"},
            {"205","Purpur Slab"},
            {"206","End Stone Bricks"},
            {"207","Beetroot Block"},
            {"208","Grass Path"},
            {"209","End Gateway"},
            {"210","Repeating Command Block"},
            {"211","Chain Command Block"},
            {"212","Frosted Ice"},
            {"213","Magma Block"},
            {"214","Nether Wart Block"},
            {"215","Red Nether Brick"},
            {"216","Bone Block"},
            {"217","Structure Void"},
            {"218","Observer"},
            {"219","White Shulker Box"},
            {"220","Orange Shulker Box"},
            {"221","Magenta Shulker Box"},
            {"222","Light Blue Shulker Box"},
            {"223","Yellow Shulker Box"},
            {"224","Lime Shulker Box"},
            {"225","Pink Shulker Box"},
            {"226","Gray Shulker Box"},
            {"227","Light Gray Shulker Box"},
            {"228","Cyan Shulker Box"},
            {"229","Purple Shulker Box"},
            {"230","Blue Shulker Box"},
            {"231","Brown Shulker Box"},
            {"232","Green Shulker Box"},
            {"233","Red Shulker Box"},
            {"234","Black Shulker Box"},
            {"235","White Glazed Terracotta"},
            {"236","Orange Glazed Terracotta"},
            {"237","Magenta Glazed Terracotta"},
            {"238","Light Blue Glazed Terracotta"},
            {"239","Yellow Glazed Terracotta"},
            {"240","Lime Glazed Terracotta"},
            {"241","Pink Glazed Terracotta"},
            {"242","Gray Glazed Terracotta"},
            {"243","Light Gray Glazed Terracotta"},
            {"244","Cyan Glazed Terracotta"},
            {"245","Purple Glazed Terracotta"},
            {"246","Blue Glazed Terracotta"},
            {"247","Brown Glazed Terracotta"},
            {"248","Green Glazed Terracotta"},
            {"249","Red Glazed Terracotta"},
            {"250","Black Glazed Terracotta"},
            {"251","White Concrete"},
            {"251:1","Orange Concrete"},
            {"251:2","Magenta Concrete"},
            {"251:3","Light Blue Concrete"},
            {"251:4","Yellow Concrete"},
            {"251:5","Lime Concrete"},
            {"251:6","Pink Concrete"},
            {"251:7","Gray Concrete"},
            {"251:8","Light Gray Concrete"},
            {"251:9","Cyan Concrete"},
            {"251:10","Purple Concrete"},
            {"251:11","Blue Concrete"},
            {"251:12","Brown Concrete"},
            {"251:13","Green Concrete"},
            {"251:14","Red Concrete"},
            {"251:15","Black Concrete"},
            {"252","White Concrete Powder"},
            {"252:1","Orange Concrete Powder"},
            {"252:2","Magenta Concrete Powder"},
            {"252:3","Light Blue Concrete Powder"},
            {"252:4","Yellow Concrete Powder"},
            {"252:5","Lime Concrete Powder"},
            {"252:6","Pink Concrete Powder"},
            {"252:7","Gray Concrete Powder"},
            {"252:8","Light Gray Concrete Powder"},
            {"252:9","Cyan Concrete Powder"},
            {"252:10","Purple Concrete Powder"},
            {"252:11","Blue Concrete Powder"},
            {"252:12","Brown Concrete Powder"},
            {"252:13","Green Concrete Powder"},
            {"252:14","Red Concrete Powder"},
            {"252:15","Black Concrete Powder"},
            {"255","Structure Block"},
            {"256","Iron Shovel"},
            {"257","Iron Pickaxe"},
            {"258","Iron Axe"},
            {"259","Flint and Steel"},
            {"260","Apple"},
            {"261","Bow"},
            {"262","Arrow"},
            {"263","Coal"},
            {"263:1","Charcoal"},
            {"264","Diamond"},
            {"265","Iron Ingot"},
            {"266","Gold Ingot"},
            {"267","Iron Sword"},
            {"268","Wooden Sword"},
            {"269","Wooden Shovel"},
            {"270","Wooden Pickaxe"},
            {"271","Wooden Axe"},
            {"272","Stone Sword"},
            {"273","Stone Shovel"},
            {"274","Stone Pickaxe"},
            {"275","Stone Axe"},
            {"276","Diamond Sword"},
            {"277","Diamond Shovel"},
            {"278","Diamond Pickaxe"},
            {"279","Diamond Axe"},
            {"280","Stick"},
            {"281","Bowl"},
            {"282","Mushroom Stew"},
            {"283","Golden Sword"},
            {"284","Golden Shovel"},
            {"285","Golden Pickaxe"},
            {"286","Golden Axe"},
            {"287","String"},
            {"288","Feather"},
            {"289","Gunpowder"},
            {"290","Wooden Hoe"},
            {"291","Stone Hoe"},
            {"292","Iron Hoe"},
            {"293","Diamond Hoe"},
            {"294","Golden Hoe"},
            {"295","Wheat Seeds"},
            {"296","Wheat"},
            {"297","Bread"},
            {"298","Leather Helmet"},
            {"299","Leather Tunic"},
            {"300","Leather Pants"},
            {"301","Leather Boots"},
            {"302","Chainmail Helmet"},
            {"303","Chainmail Chestplate"},
            {"304","Chainmail Leggings"},
            {"305","Chainmail Boots"},
            {"306","Iron Helmet"},
            {"307","Iron Chestplate"},
            {"308","Iron Leggings"},
            {"309","Iron Boots"},
            {"310","Diamond Helmet"},
            {"311","Diamond Chestplate"},
            {"312","Diamond Leggings"},
            {"313","Diamond Boots"},
            {"314","Golden Helmet"},
            {"315","Golden Chestplate"},
            {"316","Golden Leggings"},
            {"317","Golden Boots"},
            {"318","Flint"},
            {"319","Raw Porkchop"},
            {"320","Cooked Porkchop"},
            {"321","Painting"},
            {"322","Golden Apple"},
            {"322:1","Enchanted Golden Apple"},
            {"323","Sign"},
            {"324","Oak Door"},
            {"325","Bucket"},
            {"326","Water Bucket"},
            {"327","Lava Bucket"},
            {"328","Minecart"},
            {"329","Saddle"},
            {"330","Iron Door"},
            {"331","Redstone"},
            {"332","Snowball"},
            {"333","Oak Boat"},
            {"334","Leather"},
            {"335","Milk Bucket"},
            {"336","Brick"},
            {"337","Clay"},
            {"338","Sugar Canes"},
            {"339","Paper"},
            {"340","Book"},
            {"341","Slimeball"},
            {"342","Minecart with Chest"},
            {"343","Minecart with Furnace"},
            {"344","Egg"},
            {"345","Compass"},
            {"346","Fishing Rod"},
            {"347","Clock"},
            {"348","Glowstone Dust"},
            {"349","Raw Fish"},
            {"349:1","Raw Salmon"},
            {"349:2","Clownfish"},
            {"349:3","Pufferfish"},
            {"350","Cooked Fish"},
            {"350:1","Cooked Salmon"},
            {"351","Ink Sack"},
            {"351:1","Rose Red"},
            {"351:2","Cactus Green"},
            {"351:3","Coco Beans"},
            {"351:4","Lapis Lazuli"},
            {"351:5","Purple Dye"},
            {"351:6","Cyan Dye"},
            {"351:7","Light Gray Dye"},
            {"351:8","Gray Dye"},
            {"351:9","Pink Dye"},
            {"351:10","Lime Dye"},
            {"351:11","Dandelion Yellow"},
            {"351:12","Light Blue Dye"},
            {"351:13","Magenta Dye"},
            {"351:14","Orange Dye"},
            {"351:15","Bone Meal"},
            {"352","Bone"},
            {"353","Sugar"},
            {"354","Cake"},
            {"355","Bed"},
            {"356","Redstone Repeater"},
            {"357","Cookie"},
            {"358","Map"},
            {"359","Shears"},
            {"360","Melon"},
            {"361","Pumpkin Seeds"},
            {"362","Melon Seeds"},
            {"363","Raw Beef"},
            {"364","Steak"},
            {"365","Raw Chicken"},
            {"366","Cooked Chicken"},
            {"367","Rotten Flesh"},
            {"368","Ender Pearl"},
            {"369","Blaze Rod"},
            {"370","Ghast Tear"},
            {"371","Gold Nugget"},
            {"372","Nether Wart"},
            {"373","Potion"},
            {"374","Glass Bottle"},
            {"375","Spider Eye"},
            {"376","Fermented Spider Eye"},
            {"377","Blaze Powder"},
            {"378","Magma Cream"},
            {"379","Brewing Stand"},
            {"380","Cauldron"},
            {"381","Eye of Ender"},
            {"382","Glistering Melon"},
            {"383:4","Spawn Elder Guardian"},
            {"383:5","Spawn Wither Skeleton"},
            {"383:6","Spawn Stray"},
            {"383:23","Spawn Husk"},
            {"383:27","Spawn Zombie Villager"},
            {"383:28","Spawn Skeleton Horse"},
            {"383:29","Spawn Zombie Horse"},
            {"383:31","Spawn Donkey"},
            {"383:32","Spawn Mule"},
            {"383:34","Spawn Evoker"},
            {"383:35","Spawn Vex"},
            {"383:36","Spawn Vindicator"},
            {"383:50","Spawn Creeper"},
            {"383:51","Spawn Skeleton"},
            {"383:52","Spawn Spider"},
            {"383:54","Spawn Zombie"},
            {"383:55","Spawn Slime"},
            {"383:56","Spawn Ghast"},
            {"383:57","Spawn Zombie Pigman"},
            {"383:58","Spawn Enderman"},
            {"383:59","Spawn Cave Spider"},
            {"383:60","Spawn Silverfish"},
            {"383:61","Spawn Blaze"},
            {"383:62","Spawn Magma Cube"},
            {"383:65","Spawn Bat"},
            {"383:66","Spawn Witch"},
            {"383:67","Spawn Endermite"},
            {"383:68","Spawn Guardian"},
            {"383:69","Spawn Shulker"},
            {"383:90","Spawn Pig"},
            {"383:91","Spawn Sheep"},
            {"383:92","Spawn Cow"},
            {"383:93","Spawn Chicken"},
            {"383:94","Spawn Squid"},
            {"383:95","Spawn Wolf"},
            {"383:96","Spawn Mooshroom"},
            {"383:98","Spawn Ocelot"},
            {"383:100","Spawn Horse"},
            {"383:101","Spawn Rabbit"},
            {"383:102","Spawn Polar Bear"},
            {"383:103","Spawn Llama"},
            {"383:120","Spawn Villager"},
            {"384","Bottle o' Enchanting"},
            {"385","Fire Charge"},
            {"386","Book and Quill"},
            {"387","Written Book"},
            {"388","Emerald"},
            {"389","Item Frame"},
            {"390","Flower Pot"},
            {"391","Carrot"},
            {"392","Potato"},
            {"393","Baked Potato"},
            {"394","Poisonous Potato"},
            {"395","Empty Map"},
            {"396","Golden Carrot"},
            {"397","Mob Head (Skeleton)"},
            {"397:1","Mob Head (Wither Skeleton)"},
            {"397:2","Mob Head (Zombie)"},
            {"397:3","Mob Head (Human)"},
            {"397:4","Mob Head (Creeper)"},
            {"397:5","Mob Head (Dragon)"},
            {"398","Carrot on a Stick"},
            {"399","Nether Star"},
            {"400","Pumpkin Pie"},
            {"401","Firework Rocket"},
            {"402","Firework Star"},
            {"403","Enchanted Book"},
            {"404","Redstone Comparator"},
            {"405","Nether Brick"},
            {"406","Nether Quartz"},
            {"407","Minecart with TNT"},
            {"408","Minecart with Hopper"},
            {"409","Prismarine Shard"},
            {"410","Prismarine Crystals"},
            {"411","Raw Rabbit"},
            {"412","Cooked Rabbit"},
            {"413","Rabbit Stew"},
            {"414","Rabbit's Foot"},
            {"415","Rabbit Hide"},
            {"416","Armor Stand"},
            {"417","Iron Horse Armor"},
            {"418","Golden Horse Armor"},
            {"419","Diamond Horse Armor"},
            {"420","Lead"},
            {"421","Name Tag"},
            {"422","Minecart with Command Block"},
            {"423","Raw Mutton"},
            {"424","Cooked Mutton"},
            {"425","Banner"},
            {"427","Spruce Door"},
            {"428","Birch Door"},
            {"429","Jungle Door"},
            {"430","Acacia Door"},
            {"431","Dark Oak Door"},
            {"432","Chorus Fruit"},
            {"433","Popped Chorus Fruit"},
            {"434","Beetroot"},
            {"435","Beetroot Seeds"},
            {"436","Beetroot Soup"},
            {"437","Dragon's Breath"},
            {"438","Splash Potion"},
            {"439","Spectral Arrow"},
            {"440","Tipped Arrow"},
            {"441","Lingering Potion"},
            {"442","Shield"},
            {"443","Elytra"},
            {"444","Spruce Boat"},
            {"445","Birch Boat"},
            {"446","Jungle Boat"},
            {"447","Acacia Boat"},
            {"448","Dark Oak Boat"},
            {"449","Totem of Undying"},
            {"450","Shulker Shell"},
            {"452","Iron Nugget"},
            {"2256","13 Disc"},
            {"2257","Cat Disc"},
            {"2258","Blocks Disc"},
            {"2259","Chirp Disc"},
            {"2260","Far Disc"},
            {"2261","Mall Disc"},
            {"2262","Mellohi Disc"},
            {"2263","Stal Disc"},
            {"2264","Strad Disc"},
            {"2265","Ward Disc"},
            {"2266","11 Disc"},
            {"2267","Wait Disc"}
        };
        private static readonly Dictionary<string, string> blockCodes = new Dictionary<string, string>()
        {
            {"0","air"},
            {"1","stone"},
            {"1:1","stone"},
            {"1:2","stone"},
            {"1:3","stone"},
            {"1:4","stone"},
            {"1:5","stone"},
            {"1:6","stone"},
            {"2","grass"},
            {"3","dirt"},
            {"3:1","dirt"},
            {"3:2","dirt"},
            {"4","cobblestone"},
            {"5","planks"},
            {"5:1","planks"},
            {"5:2","planks"},
            {"5:3","planks"},
            {"5:4","planks"},
            {"5:5","planks"},
            {"6","sapling"},
            {"6:1","sapling"},
            {"6:2","sapling"},
            {"6:3","sapling"},
            {"6:4","sapling"},
            {"6:5","sapling"},
            {"7","bedrock"},
            {"8","flowing_water"},
            {"9","water"},
            {"10","flowing_lava"},
            {"11","lava"},
            {"12","sand"},
            {"12:1","sand"},
            {"13","gravel"},
            {"14","gold_ore"},
            {"15","iron_ore"},
            {"16","coal_ore"},
            {"17","log"},
            {"17:1","log"},
            {"17:2","log"},
            {"17:3","log"},
            {"18","leaves"},
            {"18:1","leaves"},
            {"18:2","leaves"},
            {"18:3","leaves"},
            {"19","sponge"},
            {"19:1","sponge"},
            {"20","glass"},
            {"21","lapis_ore"},
            {"22","lapis_block"},
            {"23","dispenser"},
            {"24","sandstone"},
            {"24:1","sandstone"},
            {"24:2","sandstone"},
            {"25","noteblock"},
            {"26","bed"},
            {"27","golden_rail"},
            {"28","detector_rail"},
            {"29","sticky_piston"},
            {"30","web"},
            {"31","tall_grass"},
            {"31:1","tall_grass"},
            {"31:2","tall_grass"},
            {"32","dead_bush"},
            {"33","piston"},
            {"34","piston_head"},
            {"35","wool"},
            {"35:1","wool"},
            {"35:2","wool"},
            {"35:3","wool"},
            {"35:4","wool"},
            {"35:5","wool"},
            {"35:6","wool"},
            {"35:7","wool"},
            {"35:8","wool"},
            {"35:9","wool"},
            {"35:10","wool"},
            {"35:11","wool"},
            {"35:12","wool"},
            {"35:13","wool"},
            {"35:14","wool"},
            {"35:15","wool"},
            {"37","yellow_flower"},
            {"38","red_flower"},
            {"38:1","red_flower"},
            {"38:2","red_flower"},
            {"38:3","red_flower"},
            {"38:4","red_flower"},
            {"38:5","red_flower"},
            {"38:6","red_flower"},
            {"38:7","red_flower"},
            {"38:8","red_flower"},
            {"39","brown_mushroom"},
            {"40","red_mushroom"},
            {"41","gold_block"},
            {"42","iron_block"},
            {"43","double_stone_slab"},
            {"43:1","double_stone_slab"},
            {"43:2","double_stone_slab"},
            {"43:3","double_stone_slab"},
            {"43:4","double_stone_slab"},
            {"43:5","double_stone_slab"},
            {"43:6","double_stone_slab"},
            {"43:7","double_stone_slab"},
            {"44","stone_slab"},
            {"44:1","stone_slab"},
            {"44:2","stone_slab"},
            {"44:3","stone_slab"},
            {"44:4","stone_slab"},
            {"44:5","stone_slab"},
            {"44:6","stone_slab"},
            {"44:7","stone_slab"},
            {"45","brick_block"},
            {"46","tnt"},
            {"47","bookshelf"},
            {"48","mossy_cobblestone"},
            {"49","obsidian"},
            {"50","torch"},
            {"51","fire"},
            {"52","mob_spawner"},
            {"53","oak_stairs"},
            {"54","chest"},
            {"55","redstone_wire"},
            {"56","diamond_ore"},
            {"57","diamond_block"},
            {"58","crafting_table"},
            {"59","wheat"},
            {"60","farmland"},
            {"61","furnace"},
            {"62","lit_furnace"},
            {"63","standing_sign"},
            {"64","wooden_door"},
            {"65","ladder"},
            {"66","rail"},
            {"67","stone_stairs"},
            {"68","wall_sign"},
            {"69","lever"},
            {"70","stone_pressure_plate"},
            {"71","iron_door"},
            {"72","wooden_pressure_plate"},
            {"73","redstone_ore"},
            {"74","lit_redstone_ore"},
            {"75","unlit_redstone_torch"},
            {"76","redstone_torch"},
            {"77","stone_button"},
            {"78","snow_layer"},
            {"79","ice"},
            {"80","snow"},
            {"81","cactus"},
            {"82","clay"},
            {"83","reeds"},
            {"84","jukebox"},
            {"85","fence"},
            {"86","pumpkin"},
            {"87","netherrack"},
            {"88","soul_sand"},
            {"89","glowstone"},
            {"90","portal"},
            {"91","lit_pumpkin"},
            {"92","cake"},
            {"93","unpowered_repeater"},
            {"94","powered_repeater"},
            {"95","stained_glass"},
            {"95:1","stained_glass"},
            {"95:2","stained_glass"},
            {"95:3","stained_glass"},
            {"95:4","stained_glass"},
            {"95:5","stained_glass"},
            {"95:6","stained_glass"},
            {"95:7","stained_glass"},
            {"95:8","stained_glass"},
            {"95:9","stained_glass"},
            {"95:10","stained_glass"},
            {"95:11","stained_glass"},
            {"95:12","stained_glass"},
            {"95:13","stained_glass"},
            {"95:14","stained_glass"},
            {"95:15","stained_glass"},
            {"96","trapdoor"},
            {"97","monster_egg"},
            {"97:1","monster_egg"},
            {"97:2","monster_egg"},
            {"97:3","monster_egg"},
            {"97:4","monster_egg"},
            {"97:5","monster_egg"},
            {"98","stonebrick"},
            {"98:1","stonebrick"},
            {"98:2","stonebrick"},
            {"98:3","stonebrick"},
            {"99","brown_mushroom_block"},
            {"100","red_mushroom_block"},
            {"101","iron_bars"},
            {"102","glass_pane"},
            {"103","melon_block"},
            {"104","pumpkin_stem"},
            {"105","melon_stem"},
            {"106","vine"},
            {"107","fence_gate"},
            {"108","brick_stairs"},
            {"109","stone_brick_stairs"},
            {"110","mycelium"},
            {"111","waterlily"},
            {"112","nether_brick"},
            {"113","nether_brick_fence"},
            {"114","nether_brick_stairs"},
            {"115","nether_wart"},
            {"116","enchanting_table"},
            {"117","brewing_stand"},
            {"118","cauldron"},
            {"119","end_portal"},
            {"120","end_portal_frame"},
            {"121","end_stone"},
            {"122","dragon_egg"},
            {"123","redstone_lamp"},
            {"124","lit_redstone_lamp"},
            {"125","double_wooden_slab"},
            {"125:1","double_wooden_slab"},
            {"125:2","double_wooden_slab"},
            {"125:3","double_wooden_slab"},
            {"125:4","double_wooden_slab"},
            {"125:5","double_wooden_slab"},
            {"126","wooden_slab"},
            {"126:1","wooden_slab"},
            {"126:2","wooden_slab"},
            {"126:3","wooden_slab"},
            {"126:4","wooden_slab"},
            {"126:5","wooden_slab"},
            {"127","cocoa"},
            {"128","sandstone_stairs"},
            {"129","emerald_ore"},
            {"130","ender_chest"},
            {"131","tripwire_hook"},
            {"132","tripwire_hook"},
            {"133","emerald_block"},
            {"134","spruce_stairs"},
            {"135","birch_stairs"},
            {"136","jungle_stairs"},
            {"137","command_block"},
            {"138","beacon"},
            {"139","cobblestone_wall"},
            {"139:1","cobblestone_wall"},
            {"140","flower_pot"},
            {"141","carrots"},
            {"142","potatoes"},
            {"143","wooden_button"},
            {"144","skull"},
            {"145","anvil"},
            {"146","trapped_chest"},
            {"147","light_weighted_pressure_plate"},
            {"148","heavy_weighted_pressure_plate"},
            {"149","unpowered_comparator"},
            {"150","powered_comparator"},
            {"151","daylight_detector"},
            {"152","redstone_block"},
            {"153","quartz_ore"},
            {"154","hopper"},
            {"155","quartz_block"},
            {"155:1","quartz_block"},
            {"155:2","quartz_block"},
            {"156","quartz_stairs"},
            {"157","activator_rail"},
            {"158","dropper"},
            {"159","stained_hardened_clay"},
            {"159:1","stained_hardened_clay"},
            {"159:2","stained_hardened_clay"},
            {"159:3","stained_hardened_clay"},
            {"159:4","stained_hardened_clay"},
            {"159:5","stained_hardened_clay"},
            {"159:6","stained_hardened_clay"},
            {"159:7","stained_hardened_clay"},
            {"159:8","stained_hardened_clay"},
            {"159:9","stained_hardened_clay"},
            {"159:10","stained_hardened_clay"},
            {"159:11","stained_hardened_clay"},
            {"159:12","stained_hardened_clay"},
            {"159:13","stained_hardened_clay"},
            {"159:14","stained_hardened_clay"},
            {"159:15","stained_hardened_clay"},
            {"160","stained_glass_pane"},
            {"160:1","stained_glass_pane"},
            {"160:2","stained_glass_pane"},
            {"160:3","stained_glass_pane"},
            {"160:4","stained_glass_pane"},
            {"160:5","stained_glass_pane"},
            {"160:6","stained_glass_pane"},
            {"160:7","stained_glass_pane"},
            {"160:8","stained_glass_pane"},
            {"160:9","stained_glass_pane"},
            {"160:10","stained_glass_pane"},
            {"160:11","stained_glass_pane"},
            {"160:12","stained_glass_pane"},
            {"160:13","stained_glass_pane"},
            {"160:14","stained_glass_pane"},
            {"160:15","stained_glass_pane"},
            {"161","leaves2"},
            {"161:1","leaves2"},
            {"162","log2"},
            {"162:1","log2"},
            {"163","acacia_stairs"},
            {"164","dark_oak_stairs"},
            {"165","slime"},
            {"166","barrier"},
            {"167","iron_trapdoor"},
            {"168","prismarine"},
            {"168:1","prismarine"},
            {"168:2","prismarine"},
            {"169","sea_lantern"},
            {"170","hay_block"},
            {"171","carpet"},
            {"171:1","carpet"},
            {"171:2","carpet"},
            {"171:3","carpet"},
            {"171:4","carpet"},
            {"171:5","carpet"},
            {"171:6","carpet"},
            {"171:7","carpet"},
            {"171:8","carpet"},
            {"171:9","carpet"},
            {"171:10","carpet"},
            {"171:11","carpet"},
            {"171:12","carpet"},
            {"171:13","carpet"},
            {"171:14","carpet"},
            {"171:15","carpet"},
            {"172","hardened_clay"},
            {"173","coal_block"},
            {"174","packed_ice"},
            {"175","double_plant"},
            {"175:1","double_plant"},
            {"175:2","double_plant"},
            {"175:3","double_plant"},
            {"175:4","double_plant"},
            {"175:5","double_plant"},
            {"176","standing_banner"},
            {"177","wall_banner"},
            {"178","daylight_detector_inverted"},
            {"179","red_sandstone"},
            {"179:1","red_sandstone"},
            {"179:2","red_sandstone"},
            {"180","red_sandstone_stairs"},
            {"181","double_stone_slab2"},
            {"182","stone_slab2"},
            {"183","spruce_fence_gate"},
            {"184","birch_fence_gate"},
            {"185","jungle_fence_gate"},
            {"186","dark_oak_fence_gate"},
            {"187","acacia_fence_gate"},
            {"188","spruce_fence"},
            {"189","birch_fence"},
            {"190","jungle_fence"},
            {"191","dark_oak_fence"},
            {"192","acacia_fence"},
            {"193","spruce_door"},
            {"194","birch_door"},
            {"195","jungle_door"},
            {"196","acacia_door"},
            {"197","dark_oak_door"},
            {"198","end_rod"},
            {"199","chorus_plant"},
            {"200","chorus_flower"},
            {"201","purpur_block"},
            {"202","purpur_pillar"},
            {"203","purpur_stairs"},
            {"204","purpur_double_slab"},
            {"205","purpur_slab"},
            {"206","end_bricks"},
            {"207","beetroots"},
            {"208","grass_path"},
            {"209","end_gateway"},
            {"210","repeating_command_block"},
            {"211","chain_command_block"},
            {"212","frosted_ice"},
            {"213","magma"},
            {"214","nether_wart_block"},
            {"215","red_nether_brick"},
            {"216","bone_block"},
            {"217","structure_void"},
            {"218","observer"},
            {"219","white_shulker_box"},
            {"220","orange_shulker_box"},
            {"221","magenta_shulker_box"},
            {"222","light_blue_shulker_box"},
            {"223","yellow_shulker_box"},
            {"224","lime_shulker_box"},
            {"225","pink_shulker_box"},
            {"226","gray_shulker_box"},
            {"227","silver_shulker_box"},
            {"228","cyan_shulker_box"},
            {"229","purple_shulker_box"},
            {"230","blue_shulker_box"},
            {"231","brown_shulker_box"},
            {"232","green_shulker_box"},
            {"233","red_shulker_box"},
            {"234","black_shulker_box"},
            {"235","white_glazed_terracotta"},
            {"236","orange_glazed_terracotta"},
            {"237","magenta_glazed_terracotta"},
            {"238","light_blue_glazed_terracotta"},
            {"239","yellow_glazed_terracotta"},
            {"240","lime_glazed_terracotta"},
            {"241","pink_glazed_terracotta"},
            {"242","gray_glazed_terracotta"},
            {"243","light_gray_glazed_terracotta"},
            {"244","cyan_glazed_terracotta"},
            {"245","purple_glazed_terracotta"},
            {"246","blue_glazed_terracotta"},
            {"247","brown_glazed_terracotta"},
            {"248","green_glazed_terracotta"},
            {"249","red_glazed_terracotta"},
            {"250","black_glazed_terracotta"},
            {"251","concrete"},
            {"251:1","concrete"},
            {"251:2","concrete"},
            {"251:3","concrete"},
            {"251:4","concrete"},
            {"251:5","concrete"},
            {"251:6","concrete"},
            {"251:7","concrete"},
            {"251:8","concrete"},
            {"251:9","concrete"},
            {"251:10","concrete"},
            {"251:11","concrete"},
            {"251:12","concrete"},
            {"251:13","concrete"},
            {"251:14","concrete"},
            {"251:15","concrete"},
            {"252","concrete_powder"},
            {"252:1","concrete_powder"},
            {"252:2","concrete_powder"},
            {"252:3","concrete_powder"},
            {"252:4","concrete_powder"},
            {"252:5","concrete_powder"},
            {"252:6","concrete_powder"},
            {"252:7","concrete_powder"},
            {"252:8","concrete_powder"},
            {"252:9","concrete_powder"},
            {"252:10","concrete_powder"},
            {"252:11","concrete_powder"},
            {"252:12","concrete_powder"},
            {"252:13","concrete_powder"},
            {"252:14","concrete_powder"},
            {"252:15","concrete_powder"},
            {"255","structure_block"},
            {"256","iron_shovel"},
            {"257","iron_pickaxe"},
            {"258","iron_axe"},
            {"259","flint_and_steel"},
            {"260","apple"},
            {"261","bow"},
            {"262","arrow"},
            {"263","coal"},
            {"263:1","coal"},
            {"264","diamond"},
            {"265","iron_ingot"},
            {"266","gold_ingot"},
            {"267","iron_sword"},
            {"268","wooden_sword"},
            {"269","wooden_shovel"},
            {"270","wooden_pickaxe"},
            {"271","wooden_axe"},
            {"272","stone_sword"},
            {"273","stone_shovel"},
            {"274","stone_pickaxe"},
            {"275","stone_axe"},
            {"276","diamond_sword"},
            {"277","diamond_shovel"},
            {"278","diamond_pickaxe"},
            {"279","diamond_axe"},
            {"280","stick"},
            {"281","bowl"},
            {"282","mushroom_stew"},
            {"283","golden_sword"},
            {"284","golden_shovel"},
            {"285","golden_pickaxe"},
            {"286","golden_axe"},
            {"287","string"},
            {"288","feather"},
            {"289","gunpowder"},
            {"290","wooden_hoe"},
            {"291","stone_hoe"},
            {"292","iron_hoe"},
            {"293","diamond_hoe"},
            {"294","golden_hoe"},
            {"295","wheat_seeds"},
            {"296","wheat"},
            {"297","bread"},
            {"298","leather_helmet"},
            {"299","leather_chestplate"},
            {"300","leather_leggings"},
            {"301","leather_boots"},
            {"302","chainmail_helmet"},
            {"303","chainmail_chestplate"},
            {"304","chainmail_leggings"},
            {"305","chainmail_boots"},
            {"306","iron_helmet"},
            {"307","iron_chestplate"},
            {"308","iron_leggings"},
            {"309","iron_boots"},
            {"310","diamond_helmet"},
            {"311","diamond_chestplate"},
            {"312","diamond_leggings"},
            {"313","diamond_boots"},
            {"314","golden_helmet"},
            {"315","golden_chestplate"},
            {"316","golden_leggings"},
            {"317","golden_boots"},
            {"318","flint"},
            {"319","porkchop"},
            {"320","cooked_porkchop"},
            {"321","painting"},
            {"322","golden_apple"},
            {"322:1","golden_apple"},
            {"323","sign"},
            {"324","wooden_door"},
            {"325","bucket"},
            {"326","water_bucket"},
            {"327","lava_bucket"},
            {"328","minecart"},
            {"329","saddle"},
            {"330","iron_door"},
            {"331","redstone"},
            {"332","snowball"},
            {"333","boat"},
            {"334","leather"},
            {"335","milk_bucket"},
            {"336","brick"},
            {"337","clay_ball"},
            {"338","reeds"},
            {"339","paper"},
            {"340","book"},
            {"341","slime_ball"},
            {"342","chest_minecart"},
            {"343","furnace_minecart"},
            {"344","egg"},
            {"345","compass"},
            {"346","fishing_rod"},
            {"347","clock"},
            {"348","glowstone_dust"},
            {"349","fish"},
            {"349:1","fish"},
            {"349:2","fish"},
            {"349:3","fish"},
            {"350","cooked_fish"},
            {"350:1","cooked_fish"},
            {"351","dye"},
            {"351:1","dye"},
            {"351:2","dye"},
            {"351:3","dye"},
            {"351:4","dye"},
            {"351:5","dye"},
            {"351:6","dye"},
            {"351:7","dye"},
            {"351:8","dye"},
            {"351:9","dye"},
            {"351:10","dye"},
            {"351:11","dye"},
            {"351:12","dye"},
            {"351:13","dye"},
            {"351:14","dye"},
            {"351:15","dye"},
            {"352","bone"},
            {"353","sugar"},
            {"354","cake"},
            {"355","bed"},
            {"356","repeater"},
            {"357","cookie"},
            {"358","filled_map"},
            {"359","shears"},
            {"360","melon"},
            {"361","pumpkin_seeds"},
            {"362","melon_seeds"},
            {"363","beef"},
            {"364","cooked_beef"},
            {"365","chicken"},
            {"366","cooked_chicken"},
            {"367","rotten_flesh"},
            {"368","ender_pearl"},
            {"369","blaze_rod"},
            {"370","ghast_tear"},
            {"371","gold_nugget"},
            {"372","nether_wart"},
            {"373","potion"},
            {"374","glass_bottle"},
            {"375","spider_eye"},
            {"376","fermented_spider_eye"},
            {"377","blaze_powder"},
            {"378","magma_cream"},
            {"379","brewing_stand"},
            {"380","cauldron"},
            {"381","ender_eye"},
            {"382","speckled_melon"},
            {"383:4","spawn_egg"},
            {"383:5","spawn_egg"},
            {"383:6","spawn_egg"},
            {"383:23","spawn_egg"},
            {"383:27","spawn_egg"},
            {"383:28","spawn_egg"},
            {"383:29","spawn_egg"},
            {"383:31","spawn_egg"},
            {"383:32","spawn_egg"},
            {"383:34","spawn_egg"},
            {"383:35","spawn_egg"},
            {"383:36","spawn_egg"},
            {"383:50","spawn_egg"},
            {"383:51","spawn_egg"},
            {"383:52","spawn_egg"},
            {"383:54","spawn_egg"},
            {"383:55","spawn_egg"},
            {"383:56","spawn_egg"},
            {"383:57","spawn_egg"},
            {"383:58","spawn_egg"},
            {"383:59","spawn_egg"},
            {"383:60","spawn_egg"},
            {"383:61","spawn_egg"},
            {"383:62","spawn_egg"},
            {"383:65","spawn_egg"},
            {"383:66","spawn_egg"},
            {"383:67","spawn_egg"},
            {"383:68","spawn_egg"},
            {"383:69","spawn_egg"},
            {"383:90","spawn_egg"},
            {"383:91","spawn_egg"},
            {"383:92","spawn_egg"},
            {"383:93","spawn_egg"},
            {"383:94","spawn_egg"},
            {"383:95","spawn_egg"},
            {"383:96","spawn_egg"},
            {"383:98","spawn_egg"},
            {"383:100","spawn_egg"},
            {"383:101","spawn_egg"},
            {"383:102","spawn_egg"},
            {"383:103","spawn_egg"},
            {"383:120","spawn_egg"},
            {"384","experience_bottle"},
            {"385","fire_charge"},
            {"386","writable_book"},
            {"387","written_book"},
            {"388","emerald"},
            {"389","item_frame"},
            {"390","flower_pot"},
            {"391","carrot"},
            {"392","potato"},
            {"393","baked_potato"},
            {"394","poisonous_potato"},
            {"395","map"},
            {"396","golden_carrot"},
            {"397","skull"},
            {"397:1","skull"},
            {"397:2","skull"},
            {"397:3","skull"},
            {"397:4","skull"},
            {"397:5","skull"},
            {"398","carrot_on_a_stick"},
            {"399","nether_star"},
            {"400","pumpkin_pie"},
            {"401","fireworks"},
            {"402","firework_charge"},
            {"403","enchanted_book"},
            {"404","comparator"},
            {"405","netherbrick"},
            {"406","quartz"},
            {"407","tnt_minecart"},
            {"408","hopper_minecart"},
            {"409","prismarine_shard"},
            {"410","prismarine_crystals"},
            {"411","rabbit"},
            {"412","cooked_rabbit"},
            {"413","rabbit_stew"},
            {"414","rabbit_foot"},
            {"415","rabbit_hide"},
            {"416","armor_stand"},
            {"417","iron_horse_armor"},
            {"418","golden_horse_armor"},
            {"419","diamond_horse_armor"},
            {"420","lead"},
            {"421","name_tag"},
            {"422","command_block_minecart"},
            {"423","mutton"},
            {"424","cooked_mutton"},
            {"425","banner"},
            {"427","spruce_door"},
            {"428","birch_door"},
            {"429","jungle_door"},
            {"430","acacia_door"},
            {"431","dark_oak_door"},
            {"432","chorus_fruit"},
            {"433","popped_chorus_fruit"},
            {"434","beetroot"},
            {"435","beetroot_seeds"},
            {"436","beetroot_soup"},
            {"437","dragon_breath"},
            {"438","splash_potion"},
            {"439","spectral_arrow"},
            {"440","tipped_arrow"},
            {"441","lingering_potion"},
            {"442","shield"},
            {"443","elytra"},
            {"444","spruce_boat"},
            {"445","birch_boat"},
            {"446","jungle_boat"},
            {"447","acacia_boat"},
            {"448","dark_oak_boat"},
            {"449","totem_of_undying"},
            {"450","shulker_shell"},
            {"452","iron_nugget"},
            {"2256","record_13"},
            {"2257","record_cat"},
            {"2258","record_blocks"},
            {"2259","record_chirp"},
            {"2260","record_far"},
            {"2261","record_mall"},
            {"2262","record_mellohi"},
            {"2263","record_stal"},
            {"2264","record_strad"},
            {"2265","record_ward"},
            {"2266","record_11"},
            {"2267","record_wait"}
        };

        public int BaseId { get; private set; }
        public int WorldX { get; private set; }
        public int WorldZ { get; private set; }
        public int WorldY { get; private set; }

        public BiomeType Biome { get; private set; }

        public string Id
        {
            get
            {
                if(_data != 0)
                {
                    return $"{BaseId}:{_data}";
                }
                else
                {
                    return BaseId.ToString();
                }
            }
        }

        public string Name
        {
            get
            {
                if (blockNames.ContainsKey(Id))
                {
                    return blockNames[Id];
                }
                else
                {
                    return "Unknown block";
                }
            }
        }

        public string Code {
            get
            {
                if (blockCodes.ContainsKey(Id))
                {
                    return blockCodes[Id];
                }
                else
                {
                    return "Unknown block";
                }
            }
        }

        public byte BlockLight { get; private set; }
        public byte SkyLight { get; private set; }

        private byte _data;

        public Block(int id, int y, int z, int x, byte biomeId, byte data, byte blockLight, byte skyLight)
        {
            BaseId = id;
            WorldX = x;
            WorldZ = z;
            WorldY = y;

            Biome = (BiomeType)biomeId;
            BlockLight = blockLight;
            SkyLight = skyLight;

            _data = data;
        }

        public override string ToString()
        {
            return $"{Name}[{WorldY};{WorldZ};{WorldX}] - {Biome}";
        }
    }
}
