using System;
using System.Collections.Generic;
using System.Text;

namespace Mineman.WorldParsing.Blocks
{
    public enum BiomeType
    {
        Unknown,
        Ocean = 0,
        Plains = 1,
        Desert = 2,
        Extreme_Hills = 3,
        Forest = 4,
        Taiga = 5,
        Swampland = 6,
        River = 7,
        Hell = 8,
        Sky = 9,
        Frozen_Ocean = 10,
        Frozen_River = 11,
        Ice_Plains = 12,
        Ice_Mountains = 13,
        Mushroom_Island = 14,
        Mushroom_Island_Shore = 15,
        Beach = 16,
        Desert_Hills = 17,
        Forest_Hills = 18,
        Taiga_Hills = 19,
        Extreme_Hills_Edge = 20,
        Jungle = 21,
        Jungle_Hills = 22,
        JungleEdge = 23,
        Deep_Ocean = 24,
        Stone_Beach = 25,
        Cold_Beach = 26,
        Birch_Forest = 27,
        Birch_Forest_Hills = 28,
        Roofed_Forest = 29,
        Cold_Taiga = 30,
        Cold_Taiga_Hills = 31,
        Mega_Taiga = 32,
        Mega_Taiga_Hills = 33,
        Extreme_Hills2 = 34,
        Savanna = 35,
        Savanna_Plateau = 36,
        Mesa = 37,
        Mesa_Plateau_F = 38,
        Mesa_Plateau = 39,
        The_Void = 127,
        Sunflower_Plains = 129,
        Desert_M = 130,
        Extreme_Hills_M = 131,
        Flower_Forest = 132,
        Taiga_M = 133,
        Swampland_M = 134,
        Ice_Plains_Spikes = 140,
        Jungle_M = 149,
        JungleEdge_M = 151,
        Birch_Forest_M = 155,
        Birch_Forest_Hills_M = 156,
        Roofed_Forest_M = 157,
        Cold_Taiga_M = 158,
        Mega_Spruce_Taiga = 160,
        Redwood_Taiga_Hills_M = 161,
        Extreme_Hills2_M = 162,
        Savanna_M = 163,
        Savanna_Plateau_M = 164,
        Mesa_Bryce = 165,
        Mesa_Plateau_F_M = 166,
        Mesa_Plateau_M = 167,
    }

    public class Block
    {
        private static readonly Dictionary<string, string> blockNames = new Dictionary<string, string>
        {
            {"0","Air"},
            {"1","Stone"},
            {"1:1","Granite"},
            {"1:2","Polished Granite"},
            {"1:3","Diorite"},
            {"1:4","Polished Diorite"},
            {"1:5","Andesite"},
            {"1:6","Polished Andesite"},
            {"2","Grass"},
            {"3","Dirt"},
            {"3:1","Coarse Dirt"},
            {"3:2","Podzol"},
            {"4","Cobblestone"},
            {"5","Oak Wood Plank"},
            {"5:1","Spruce Wood Plank"},
            {"5:2","Birch Wood Plank"},
            {"5:3","Jungle Wood Plank"},
            {"5:4","Acacia Wood Plank"},
            {"5:5","Dark Oak Wood Plank"},
            {"6","Oak Sapling"},
            {"6:1","Spruce Sapling"},
            {"6:2","Birch Sapling"},
            {"6:3","Jungle Sapling"},
            {"6:4","Acacia Sapling"},
            {"6:5","Dark Oak Sapling"},
            {"7","Bedrock"},
            {"8","Flowing Water"},
            {"9","Still Water"},
            {"10","Flowing Lava"},
            {"11","Still Lava"},
            {"12","Sand"},
            {"12:1","Red Sand"},
            {"13","Gravel"},
            {"14","Gold Ore"},
            {"15","Iron Ore"},
            {"16","Coal Ore"},
            {"17","Oak Wood"},
            {"17:1","Spruce Wood"},
            {"17:2","Birch Wood"},
            {"17:3","Jungle Wood"},
            {"18","Oak Leaves"},
            {"18:1","Spruce Leaves"},
            {"18:2","Birch Leaves"},
            {"18:3","Jungle Leaves"},
            {"19","Sponge"},
            {"19:1","Wet Sponge"},
            {"20","Glass"},
            {"21","Lapis Lazuli Ore"},
            {"22","Lapis Lazuli Block"},
            {"23","Dispenser"},
            {"24","Sandstone"},
            {"24:1","Chiseled Sandstone"},
            {"24:2","Smooth Sandstone"},
            {"25","Note Block"},
            {"26","Bed"},
            {"27","Powered Rail"},
            {"28","Detector Rail"},
            {"29","Sticky Piston"},
            {"30","Cobweb"},
            {"31","Dead Shrub"},
            {"31:1","Grass"},
            {"31:2","Fern"},
            {"32","Dead Bush"},
            {"33","Piston"},
            {"34","Piston Head"},
            {"35","White Wool"},
            {"35:1","Orange Wool"},
            {"35:2","Magenta Wool"},
            {"35:3","Light Blue Wool"},
            {"35:4","Yellow Wool"},
            {"35:5","Lime Wool"},
            {"35:6","Pink Wool"},
            {"35:7","Gray Wool"},
            {"35:8","Light Gray Wool"},
            {"35:9","Cyan Wool"},
            {"35:10","Purple Wool"},
            {"35:11","Blue Wool"},
            {"35:12","Brown Wool"},
            {"35:13","Green Wool"},
            {"35:14","Red Wool"},
            {"35:15","Black Wool"},
            {"37","Dandelion"},
            {"38","Poppy"},
            {"38:1","Blue Orchid"},
            {"38:2","Allium"},
            {"38:3","Azure Bluet"},
            {"38:4","Red Tulip"},
            {"38:5","Orange Tulip"},
            {"38:6","White Tulip"},
            {"38:7","Pink Tulip"},
            {"38:8","Oxeye Daisy"},
            {"39","Brown Mushroom"},
            {"40","Red Mushroom"},
            {"41","Gold Block"},
            {"42","Iron Block"},
            {"43","Double Stone Slab"},
            {"43:1","Double Sandstone Slab"},
            {"43:2","Double Wooden Slab"},
            {"43:3","Double Cobblestone Slab"},
            {"43:4","Double Brick Slab"},
            {"43:5","Double Stone Brick Slab"},
            {"43:6","Double Nether Brick Slab"},
            {"43:7","Double Quartz Slab"},
            {"44","Stone Slab"},
            {"44:1","Sandstone Slab"},
            {"44:2","Wooden Slab"},
            {"44:3","Cobblestone Slab"},
            {"44:4","Brick Slab"},
            {"44:5","Stone Brick Slab"},
            {"44:6","Nether Brick Slab"},
            {"44:7","Quartz Slab"},
            {"45","Bricks"},
            {"46","TNT"},
            {"47","Bookshelf"},
            {"48","Moss Stone"},
            {"49","Obsidian"},
            {"50","Torch"},
            {"51","Fire"},
            {"52","Monster Spawner"},
            {"53","Oak Wood Stairs"},
            {"54","Chest"},
            {"55","Redstone Wire"},
            {"56","Diamond Ore"},
            {"57","Diamond Block"},
            {"58","Crafting Table"},
            {"59","Wheat Crops"},
            {"60","Farmland"},
            {"61","Furnace"},
            {"62","Burning Furnace"},
            {"63","Standing Sign Block"},
            {"64","Oak Door Block"},
            {"65","Ladder"},
            {"66","Rail"},
            {"67","Cobblestone Stairs"},
            {"68","Wall-mounted Sign Block"},
            {"69","Lever"},
            {"70","Stone Pressure Plate"},
            {"71","Iron Door Block"},
            {"72","Wooden Pressure Plate"},
            {"73","Redstone Ore"},
            {"74","Glowing Redstone Ore"},
            {"75","Redstone Torch (off)"},
            {"76","Redstone Torch (on)"},
            {"77","Stone Button"},
            {"78","Snow"},
            {"79","Ice"},
            {"80","Snow Block"},
            {"81","Cactus"},
            {"82","Clay"},
            {"83","Sugar Canes"},
            {"84","Jukebox"},
            {"85","Oak Fence"},
            {"86","Pumpkin"},
            {"87","Netherrack"},
            {"88","Soul Sand"},
            {"89","Glowstone"},
            {"90","Nether Portal"},
            {"91","Jack o'Lantern"},
            {"92","Cake Block"},
            {"93","Redstone Repeater Block (off)"},
            {"94","Redstone Repeater Block (on)"},
            {"95","White Stained Glass"},
            {"95:1","Orange Stained Glass"},
            {"95:2","Magenta Stained Glass"},
            {"95:3","Light Blue Stained Glass"},
            {"95:4","Yellow Stained Glass"},
            {"95:5","Lime Stained Glass"},
            {"95:6","Pink Stained Glass"},
            {"95:7","Gray Stained Glass"},
            {"95:8","Light Gray Stained Glass"},
            {"95:9","Cyan Stained Glass"},
            {"95:10","Purple Stained Glass"},
            {"95:11","Blue Stained Glass"},
            {"95:12","Brown Stained Glass"},
            {"95:13","Green Stained Glass"},
            {"95:14","Red Stained Glass"},
            {"95:15","Black Stained Glass"},
            {"96","Wooden Trapdoor"},
            {"97","Stone Monster Egg"},
            {"97:1","Cobblestone Monster Egg"},
            {"97:2","Stone Brick Monster Egg"},
            {"97:3","Mossy Stone Brick Monster Egg"},
            {"97:4","Cracked Stone Brick Monster Egg"},
            {"97:5","Chiseled Stone Brick Monster Egg"},
            {"98","Stone Bricks"},
            {"98:1","Mossy Stone Bricks"},
            {"98:2","Cracked Stone Bricks"},
            {"98:3","Chiseled Stone Bricks"},
            {"99","Brown Mushroom Block"},
            {"100","Red Mushroom Block"},
            {"101","Iron Bars"},
            {"102","Glass Pane"},
            {"103","Melon Block"},
            {"104","Pumpkin Stem"},
            {"105","Melon Stem"},
            {"106","Vines"},
            {"107","Oak Fence Gate"},
            {"108","Brick Stairs"},
            {"109","Stone Brick Stairs"},
            {"110","Mycelium"},
            {"111","Lily Pad"},
            {"112","Nether Brick"},
            {"113","Nether Brick Fence"},
            {"114","Nether Brick Stairs"},
            {"115","Nether Wart"},
            {"116","Enchantment Table"},
            {"117","Brewing Stand"},
            {"118","Cauldron"},
            {"119","End Portal"},
            {"120","End Portal Frame"},
            {"121","End Stone"},
            {"122","Dragon Egg"},
            {"123","Redstone Lamp (inactive)"},
            {"124","Redstone Lamp (active)"},
            {"125","Double Oak Wood Slab"},
            {"125:1","Double Spruce Wood Slab"},
            {"125:2","Double Birch Wood Slab"},
            {"125:3","Double Jungle Wood Slab"},
            {"125:4","Double Acacia Wood Slab"},
            {"125:5","Double Dark Oak Wood Slab"},
            {"126","Oak Wood Slab"},
            {"126:1","Spruce Wood Slab"},
            {"126:2","Birch Wood Slab"},
            {"126:3","Jungle Wood Slab"},
            {"126:4","Acacia Wood Slab"},
            {"126:5","Dark Oak Wood Slab"},
            {"127","Cocoa"},
            {"128","Sandstone Stairs"},
            {"129","Emerald Ore"},
            {"130","Ender Chest"},
            {"131","Tripwire Hook"},
            {"132","Tripwire"},
            {"133","Emerald Block"},
            {"134","Spruce Wood Stairs"},
            {"135","Birch Wood Stairs"},
            {"136","Jungle Wood Stairs"},
            {"137","Command Block"},
            {"138","Beacon"},
            {"139","Cobblestone Wall"},
            {"139:1","Mossy Cobblestone Wall"},
            {"140","Flower Pot"},
            {"141","Carrots"},
            {"142","Potatoes"},
            {"143","Wooden Button"},
            {"144","Mob Head"},
            {"145","Anvil"},
            {"146","Trapped Chest"},
            {"147","Weighted Pressure Plate (light)"},
            {"148","Weighted Pressure Plate (heavy)"},
            {"149","Redstone Comparator (inactive)"},
            {"150","Redstone Comparator (active)"},
            {"151","Daylight Sensor"},
            {"152","Redstone Block"},
            {"153","Nether Quartz Ore"},
            {"154","Hopper"},
            {"155","Quartz Block"},
            {"155:1","Chiseled Quartz Block"},
            {"155:2","Pillar Quartz Block"},
            {"156","Quartz Stairs"},
            {"157","Activator Rail"},
            {"158","Dropper"},
            {"159","White Hardened Clay"},
            {"159:1","Orange Hardened Clay"},
            {"159:2","Magenta Hardened Clay"},
            {"159:3","Light Blue Hardened Clay"},
            {"159:4","Yellow Hardened Clay"},
            {"159:5","Lime Hardened Clay"},
            {"159:6","Pink Hardened Clay"},
            {"159:7","Gray Hardened Clay"},
            {"159:8","Light Gray Hardened Clay"},
            {"159:9","Cyan Hardened Clay"},
            {"159:10","Purple Hardened Clay"},
            {"159:11","Blue Hardened Clay"},
            {"159:12","Brown Hardened Clay"},
            {"159:13","Green Hardened Clay"},
            {"159:14","Red Hardened Clay"},
            {"159:15","Black Hardened Clay"},
            {"160","White Stained Glass Pane"},
            {"160:1","Orange Stained Glass Pane"},
            {"160:2","Magenta Stained Glass Pane"},
            {"160:3","Light Blue Stained Glass Pane"},
            {"160:4","Yellow Stained Glass Pane"},
            {"160:5","Lime Stained Glass Pane"},
            {"160:6","Pink Stained Glass Pane"},
            {"160:7","Gray Stained Glass Pane"},
            {"160:8","Light Gray Stained Glass Pane"},
            {"160:9","Cyan Stained Glass Pane"},
            {"160:10","Purple Stained Glass Pane"},
            {"160:11","Blue Stained Glass Pane"},
            {"160:12","Brown Stained Glass Pane"},
            {"160:13","Green Stained Glass Pane"},
            {"160:14","Red Stained Glass Pane"},
            {"160:15","Black Stained Glass Pane"},
            {"161","Acacia Leaves"},
            {"161:1","Dark Oak Leaves"},
            {"162","Acacia Wood"},
            {"162:1","Dark Oak Wood"},
            {"163","Acacia Wood Stairs"},
            {"164","Dark Oak Wood Stairs"},
            {"165","Slime Block"},
            {"166","Barrier"},
            {"167","Iron Trapdoor"},
            {"168","Prismarine"},
            {"168:1","Prismarine Bricks"},
            {"168:2","Dark Prismarine"},
            {"169","Sea Lantern"},
            {"170","Hay Bale"},
            {"171","White Carpet"},
            {"171:1","Orange Carpet"},
            {"171:2","Magenta Carpet"},
            {"171:3","Light Blue Carpet"},
            {"171:4","Yellow Carpet"},
            {"171:5","Lime Carpet"},
            {"171:6","Pink Carpet"},
            {"171:7","Gray Carpet"},
            {"171:8","Light Gray Carpet"},
            {"171:9","Cyan Carpet"},
            {"171:10","Purple Carpet"},
            {"171:11","Blue Carpet"},
            {"171:12","Brown Carpet"},
            {"171:13","Green Carpet"},
            {"171:14","Red Carpet"},
            {"171:15","Black Carpet"},
            {"172","Hardened Clay"},
            {"173","Block of Coal"},
            {"174","Packed Ice"},
            {"175","Sunflower"},
            {"175:1","Lilac"},
            {"175:2","Double Tallgrass"},
            {"175:3","Large Fern"},
            {"175:4","Rose Bush"},
            {"175:5","Peony"},
            {"176","Free-standing Banner"},
            {"177","Wall-mounted Banner"},
            {"178","Inverted Daylight Sensor"},
            {"179","Red Sandstone"},
            {"179:1","Chiseled Red Sandstone"},
            {"179:2","Smooth Red Sandstone"},
            {"180","Red Sandstone Stairs"},
            {"181","Double Red Sandstone Slab"},
            {"182","Red Sandstone Slab"},
            {"183","Spruce Fence Gate"},
            {"184","Birch Fence Gate"},
            {"185","Jungle Fence Gate"},
            {"186","Dark Oak Fence Gate"},
            {"187","Acacia Fence Gate"},
            {"188","Spruce Fence"},
            {"189","Birch Fence"},
            {"190","Jungle Fence"},
            {"191","Dark Oak Fence"},
            {"192","Acacia Fence"},
            {"193","Spruce Door Block"},
            {"194","Birch Door Block"},
            {"195","Jungle Door Block"},
            {"196","Acacia Door Block"},
            {"197","Dark Oak Door Block"},
            {"198","End Rod"},
            {"199","Chorus Plant"},
            {"200","Chorus Flower"},
            {"201","Purpur Block"},
            {"202","Purpur Pillar"},
            {"203","Purpur Stairs"},
            {"204","Purpur Double Slab"},
            {"205","Purpur Slab"},
            {"206","End Stone Bricks"},
            {"207","Beetroot Block"},
            {"208","Grass Path"},
            {"209","End Gateway"},
            {"210","Repeating Command Block"},
            {"211","Chain Command Block"},
            {"212","Frosted Ice"},
            {"213","Magma Block"},
            {"214","Nether Wart Block"},
            {"215","Red Nether Brick"},
            {"216","Bone Block"},
            {"217","Structure Void"},
            {"218","Observer"},
            {"219","White Shulker Box"},
            {"220","Orange Shulker Box"},
            {"221","Magenta Shulker Box"},
            {"222","Light Blue Shulker Box"},
            {"223","Yellow Shulker Box"},
            {"224","Lime Shulker Box"},
            {"225","Pink Shulker Box"},
            {"226","Gray Shulker Box"},
            {"227","Light Gray Shulker Box"},
            {"228","Cyan Shulker Box"},
            {"229","Purple Shulker Box"},
            {"230","Blue Shulker Box"},
            {"231","Brown Shulker Box"},
            {"232","Green Shulker Box"},
            {"233","Red Shulker Box"},
            {"234","Black Shulker Box"},
            {"235","White Glazed Terracotta"},
            {"236","Orange Glazed Terracotta"},
            {"237","Magenta Glazed Terracotta"},
            {"238","Light Blue Glazed Terracotta"},
            {"239","Yellow Glazed Terracotta"},
            {"240","Lime Glazed Terracotta"},
            {"241","Pink Glazed Terracotta"},
            {"242","Gray Glazed Terracotta"},
            {"243","Light Gray Glazed Terracotta"},
            {"244","Cyan Glazed Terracotta"},
            {"245","Purple Glazed Terracotta"},
            {"246","Blue Glazed Terracotta"},
            {"247","Brown Glazed Terracotta"},
            {"248","Green Glazed Terracotta"},
            {"249","Red Glazed Terracotta"},
            {"250","Black Glazed Terracotta"},
            {"251","White Concrete"},
            {"251:1","Orange Concrete"},
            {"251:2","Magenta Concrete"},
            {"251:3","Light Blue Concrete"},
            {"251:4","Yellow Concrete"},
            {"251:5","Lime Concrete"},
            {"251:6","Pink Concrete"},
            {"251:7","Gray Concrete"},
            {"251:8","Light Gray Concrete"},
            {"251:9","Cyan Concrete"},
            {"251:10","Purple Concrete"},
            {"251:11","Blue Concrete"},
            {"251:12","Brown Concrete"},
            {"251:13","Green Concrete"},
            {"251:14","Red Concrete"},
            {"251:15","Black Concrete"},
            {"252","White Concrete Powder"},
            {"252:1","Orange Concrete Powder"},
            {"252:2","Magenta Concrete Powder"},
            {"252:3","Light Blue Concrete Powder"},
            {"252:4","Yellow Concrete Powder"},
            {"252:5","Lime Concrete Powder"},
            {"252:6","Pink Concrete Powder"},
            {"252:7","Gray Concrete Powder"},
            {"252:8","Light Gray Concrete Powder"},
            {"252:9","Cyan Concrete Powder"},
            {"252:10","Purple Concrete Powder"},
            {"252:11","Blue Concrete Powder"},
            {"252:12","Brown Concrete Powder"},
            {"252:13","Green Concrete Powder"},
            {"252:14","Red Concrete Powder"},
            {"252:15","Black Concrete Powder"},
            {"255","Structure Block"},
            {"256","Iron Shovel"},
            {"257","Iron Pickaxe"},
            {"258","Iron Axe"},
            {"259","Flint and Steel"},
            {"260","Apple"},
            {"261","Bow"},
            {"262","Arrow"},
            {"263","Coal"},
            {"263:1","Charcoal"},
            {"264","Diamond"},
            {"265","Iron Ingot"},
            {"266","Gold Ingot"},
            {"267","Iron Sword"},
            {"268","Wooden Sword"},
            {"269","Wooden Shovel"},
            {"270","Wooden Pickaxe"},
            {"271","Wooden Axe"},
            {"272","Stone Sword"},
            {"273","Stone Shovel"},
            {"274","Stone Pickaxe"},
            {"275","Stone Axe"},
            {"276","Diamond Sword"},
            {"277","Diamond Shovel"},
            {"278","Diamond Pickaxe"},
            {"279","Diamond Axe"},
            {"280","Stick"},
            {"281","Bowl"},
            {"282","Mushroom Stew"},
            {"283","Golden Sword"},
            {"284","Golden Shovel"},
            {"285","Golden Pickaxe"},
            {"286","Golden Axe"},
            {"287","String"},
            {"288","Feather"},
            {"289","Gunpowder"},
            {"290","Wooden Hoe"},
            {"291","Stone Hoe"},
            {"292","Iron Hoe"},
            {"293","Diamond Hoe"},
            {"294","Golden Hoe"},
            {"295","Wheat Seeds"},
            {"296","Wheat"},
            {"297","Bread"},
            {"298","Leather Helmet"},
            {"299","Leather Tunic"},
            {"300","Leather Pants"},
            {"301","Leather Boots"},
            {"302","Chainmail Helmet"},
            {"303","Chainmail Chestplate"},
            {"304","Chainmail Leggings"},
            {"305","Chainmail Boots"},
            {"306","Iron Helmet"},
            {"307","Iron Chestplate"},
            {"308","Iron Leggings"},
            {"309","Iron Boots"},
            {"310","Diamond Helmet"},
            {"311","Diamond Chestplate"},
            {"312","Diamond Leggings"},
            {"313","Diamond Boots"},
            {"314","Golden Helmet"},
            {"315","Golden Chestplate"},
            {"316","Golden Leggings"},
            {"317","Golden Boots"},
            {"318","Flint"},
            {"319","Raw Porkchop"},
            {"320","Cooked Porkchop"},
            {"321","Painting"},
            {"322","Golden Apple"},
            {"322:1","Enchanted Golden Apple"},
            {"323","Sign"},
            {"324","Oak Door"},
            {"325","Bucket"},
            {"326","Water Bucket"},
            {"327","Lava Bucket"},
            {"328","Minecart"},
            {"329","Saddle"},
            {"330","Iron Door"},
            {"331","Redstone"},
            {"332","Snowball"},
            {"333","Oak Boat"},
            {"334","Leather"},
            {"335","Milk Bucket"},
            {"336","Brick"},
            {"337","Clay"},
            {"338","Sugar Canes"},
            {"339","Paper"},
            {"340","Book"},
            {"341","Slimeball"},
            {"342","Minecart with Chest"},
            {"343","Minecart with Furnace"},
            {"344","Egg"},
            {"345","Compass"},
            {"346","Fishing Rod"},
            {"347","Clock"},
            {"348","Glowstone Dust"},
            {"349","Raw Fish"},
            {"349:1","Raw Salmon"},
            {"349:2","Clownfish"},
            {"349:3","Pufferfish"},
            {"350","Cooked Fish"},
            {"350:1","Cooked Salmon"},
            {"351","Ink Sack"},
            {"351:1","Rose Red"},
            {"351:2","Cactus Green"},
            {"351:3","Coco Beans"},
            {"351:4","Lapis Lazuli"},
            {"351:5","Purple Dye"},
            {"351:6","Cyan Dye"},
            {"351:7","Light Gray Dye"},
            {"351:8","Gray Dye"},
            {"351:9","Pink Dye"},
            {"351:10","Lime Dye"},
            {"351:11","Dandelion Yellow"},
            {"351:12","Light Blue Dye"},
            {"351:13","Magenta Dye"},
            {"351:14","Orange Dye"},
            {"351:15","Bone Meal"},
            {"352","Bone"},
            {"353","Sugar"},
            {"354","Cake"},
            {"355","Bed"},
            {"356","Redstone Repeater"},
            {"357","Cookie"},
            {"358","Map"},
            {"359","Shears"},
            {"360","Melon"},
            {"361","Pumpkin Seeds"},
            {"362","Melon Seeds"},
            {"363","Raw Beef"},
            {"364","Steak"},
            {"365","Raw Chicken"},
            {"366","Cooked Chicken"},
            {"367","Rotten Flesh"},
            {"368","Ender Pearl"},
            {"369","Blaze Rod"},
            {"370","Ghast Tear"},
            {"371","Gold Nugget"},
            {"372","Nether Wart"},
            {"373","Potion"},
            {"374","Glass Bottle"},
            {"375","Spider Eye"},
            {"376","Fermented Spider Eye"},
            {"377","Blaze Powder"},
            {"378","Magma Cream"},
            {"379","Brewing Stand"},
            {"380","Cauldron"},
            {"381","Eye of Ender"},
            {"382","Glistering Melon"},
            {"383:4","Spawn Elder Guardian"},
            {"383:5","Spawn Wither Skeleton"},
            {"383:6","Spawn Stray"},
            {"383:23","Spawn Husk"},
            {"383:27","Spawn Zombie Villager"},
            {"383:28","Spawn Skeleton Horse"},
            {"383:29","Spawn Zombie Horse"},
            {"383:31","Spawn Donkey"},
            {"383:32","Spawn Mule"},
            {"383:34","Spawn Evoker"},
            {"383:35","Spawn Vex"},
            {"383:36","Spawn Vindicator"},
            {"383:50","Spawn Creeper"},
            {"383:51","Spawn Skeleton"},
            {"383:52","Spawn Spider"},
            {"383:54","Spawn Zombie"},
            {"383:55","Spawn Slime"},
            {"383:56","Spawn Ghast"},
            {"383:57","Spawn Zombie Pigman"},
            {"383:58","Spawn Enderman"},
            {"383:59","Spawn Cave Spider"},
            {"383:60","Spawn Silverfish"},
            {"383:61","Spawn Blaze"},
            {"383:62","Spawn Magma Cube"},
            {"383:65","Spawn Bat"},
            {"383:66","Spawn Witch"},
            {"383:67","Spawn Endermite"},
            {"383:68","Spawn Guardian"},
            {"383:69","Spawn Shulker"},
            {"383:90","Spawn Pig"},
            {"383:91","Spawn Sheep"},
            {"383:92","Spawn Cow"},
            {"383:93","Spawn Chicken"},
            {"383:94","Spawn Squid"},
            {"383:95","Spawn Wolf"},
            {"383:96","Spawn Mooshroom"},
            {"383:98","Spawn Ocelot"},
            {"383:100","Spawn Horse"},
            {"383:101","Spawn Rabbit"},
            {"383:102","Spawn Polar Bear"},
            {"383:103","Spawn Llama"},
            {"383:120","Spawn Villager"},
            {"384","Bottle o' Enchanting"},
            {"385","Fire Charge"},
            {"386","Book and Quill"},
            {"387","Written Book"},
            {"388","Emerald"},
            {"389","Item Frame"},
            {"390","Flower Pot"},
            {"391","Carrot"},
            {"392","Potato"},
            {"393","Baked Potato"},
            {"394","Poisonous Potato"},
            {"395","Empty Map"},
            {"396","Golden Carrot"},
            {"397","Mob Head (Skeleton)"},
            {"397:1","Mob Head (Wither Skeleton)"},
            {"397:2","Mob Head (Zombie)"},
            {"397:3","Mob Head (Human)"},
            {"397:4","Mob Head (Creeper)"},
            {"397:5","Mob Head (Dragon)"},
            {"398","Carrot on a Stick"},
            {"399","Nether Star"},
            {"400","Pumpkin Pie"},
            {"401","Firework Rocket"},
            {"402","Firework Star"},
            {"403","Enchanted Book"},
            {"404","Redstone Comparator"},
            {"405","Nether Brick"},
            {"406","Nether Quartz"},
            {"407","Minecart with TNT"},
            {"408","Minecart with Hopper"},
            {"409","Prismarine Shard"},
            {"410","Prismarine Crystals"},
            {"411","Raw Rabbit"},
            {"412","Cooked Rabbit"},
            {"413","Rabbit Stew"},
            {"414","Rabbit's Foot"},
            {"415","Rabbit Hide"},
            {"416","Armor Stand"},
            {"417","Iron Horse Armor"},
            {"418","Golden Horse Armor"},
            {"419","Diamond Horse Armor"},
            {"420","Lead"},
            {"421","Name Tag"},
            {"422","Minecart with Command Block"},
            {"423","Raw Mutton"},
            {"424","Cooked Mutton"},
            {"425","Banner"},
            {"427","Spruce Door"},
            {"428","Birch Door"},
            {"429","Jungle Door"},
            {"430","Acacia Door"},
            {"431","Dark Oak Door"},
            {"432","Chorus Fruit"},
            {"433","Popped Chorus Fruit"},
            {"434","Beetroot"},
            {"435","Beetroot Seeds"},
            {"436","Beetroot Soup"},
            {"437","Dragon's Breath"},
            {"438","Splash Potion"},
            {"439","Spectral Arrow"},
            {"440","Tipped Arrow"},
            {"441","Lingering Potion"},
            {"442","Shield"},
            {"443","Elytra"},
            {"444","Spruce Boat"},
            {"445","Birch Boat"},
            {"446","Jungle Boat"},
            {"447","Acacia Boat"},
            {"448","Dark Oak Boat"},
            {"449","Totem of Undying"},
            {"450","Shulker Shell"},
            {"452","Iron Nugget"},
            {"2256","13 Disc"},
            {"2257","Cat Disc"},
            {"2258","Blocks Disc"},
            {"2259","Chirp Disc"},
            {"2260","Far Disc"},
            {"2261","Mall Disc"},
            {"2262","Mellohi Disc"},
            {"2263","Stal Disc"},
            {"2264","Strad Disc"},
            {"2265","Ward Disc"},
            {"2266","11 Disc"},
            {"2267","Wait Disc"}
        };

        public int Id { get; private set; }
        public int WorldX { get; private set; }
        public int WorldZ { get; private set; }
        public int WorldY { get; private set; }

        public BiomeType Biome { get; private set; }

        public string Name
        {
            get
            {
                string search = Id.ToString();
                if (_data != 0)
                {
                    search += ":" + _data.ToString();
                }

                if (blockNames.ContainsKey(search))
                {
                    return blockNames[search];
                }
                else
                {
                    return "Unknown block";
                }
            }
        }

        private byte _data;

        public Block(int id, int y, int z, int x, byte biomeId, byte data)
        {
            Id = id;
            WorldX = x;
            WorldZ = z;
            WorldY = y;

            Biome = (BiomeType)biomeId;

            _data = data;
        }

        public override string ToString()
        {
            return $"{Name}[{WorldY};{WorldZ};{WorldX}] - {Biome}";
        }
    }
}
